spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: postgresql


  mail:
    host: localhost
    port: 1025
    protocol: smtp
    properties:
      mail:
        smtp:
          trust: '*'
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    username: admin
    password: admin
    from: BOOK-SOCIAL



  application:
    security:
        jwt:
          secret-key: 4BA7D8CBBACA69DDAE81C764478E5
          expiration-time: 86400000


server:
  port: 8182
  servlet:
    context-path: /api/v1